name: Publish Gradle Plugin

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=$(echo "${GITHUB_REF#refs/tags/}" | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Validate version format
        run: |
          # Accepts semantic versions like 1.2.3, 1.2.3-beta, 1.2.3+build, etc.
          if ! [[ "${{ steps.get_version.outputs.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+([\-+][A-Za-z0-9\.\-]+)?$ ]]; then
            echo "Error: Invalid version format: ${{ steps.get_version.outputs.VERSION }}"
            exit 1
          fi
      - name: Publish to Gradle Plugin Portal
        run: ./gradlew publishPlugins -Pversion=${{ steps.get_version.outputs.VERSION }}
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
